-- PostgreSQL 15+ / Neon. Apply using php bin/migrate.php; never from a web request.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  username   VARCHAR(80)      NOT NULL,
  email      VARCHAR(180)     NOT NULL DEFAULT '',
  password   VARCHAR(255)     NOT NULL,
  full_name  VARCHAR(120)     NOT NULL DEFAULT '',
  role       VARCHAR(30) NOT NULL DEFAULT 'admin' CHECK (role IN ('superadmin','admin','editor')),
  is_active  SMALLINT       NOT NULL DEFAULT 1,
  last_login TIMESTAMPTZ             NULL,
  created_at TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(120) NOT NULL,
  slug        VARCHAR(160) NOT NULL,
  description TEXT             NULL,
  post_type   VARCHAR(30)  NOT NULL DEFAULT 'all',
  sort_order  INT          NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS posts (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title           VARCHAR(400)     NOT NULL,
  slug            VARCHAR(450)     NOT NULL,
  summary         TEXT                 NULL,
  content         TEXT             NULL,
  featured_image  VARCHAR(350)         NULL,
  featured_video  VARCHAR(500)         NULL,
  post_type       VARCHAR(30) NOT NULL DEFAULT 'news',
  page_section    VARCHAR(300)     NOT NULL DEFAULT 'home,news',
  category_id     INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  author_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('published','draft')),
  is_featured     SMALLINT       NOT NULL DEFAULT 0,
  views           INTEGER     NOT NULL DEFAULT 0,
  published_at    TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS posts_idx_status_type ON posts (status, post_type);

CREATE INDEX IF NOT EXISTS posts_idx_category ON posts (category_id);

CREATE INDEX IF NOT EXISTS posts_idx_published ON posts (published_at);

CREATE TABLE IF NOT EXISTS post_images (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id    INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  image_path VARCHAR(350) NOT NULL,
  alt_text   VARCHAR(200)     NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS post_images_idx_post ON post_images (post_id);

CREATE TABLE IF NOT EXISTS lessons (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(400) NOT NULL,
  slug           VARCHAR(450) NOT NULL,
  subject        VARCHAR(150)     NULL,
  teacher        VARCHAR(150)     NULL,
  content        TEXT         NULL,
  summary        TEXT             NULL,
  audio_file     VARCHAR(350)     NULL,
  featured_image VARCHAR(350)     NULL,
  level          VARCHAR(30) DEFAULT 'beginner',
  status         VARCHAR(30) NOT NULL DEFAULT 'draft',
  page_section   VARCHAR(255) NOT NULL DEFAULT 'home',
  sort_order     INT          NOT NULL DEFAULT 0,
  views          INTEGER NOT NULL DEFAULT 0,
  created_by     INTEGER     NULL,
  created_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS lessons_idx_status ON lessons (status);

CREATE TABLE IF NOT EXISTS contact_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name       VARCHAR(200) NOT NULL,
  email      VARCHAR(200)     NULL,
  phone      VARCHAR(50)      NULL,
  subject    VARCHAR(300)     NULL,
  message    TEXT         NOT NULL,
  ip_address VARCHAR(45)      NULL,
  is_read    SMALLINT   NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS contact_messages_idx_is_read ON contact_messages (is_read);

CREATE INDEX IF NOT EXISTS contact_messages_idx_created ON contact_messages (created_at);

CREATE TABLE IF NOT EXISTS post_likes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id    INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  ip_hash    VARCHAR(64)  NOT NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (post_id, ip_hash)
);

CREATE INDEX IF NOT EXISTS post_likes_idx_post ON post_likes (post_id);

CREATE TABLE IF NOT EXISTS media_files (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ref_type   VARCHAR(30)  NOT NULL DEFAULT 'post',
  ref_id     INTEGER NOT NULL,
  kind       VARCHAR(30) NOT NULL DEFAULT 'image',
  file_path  VARCHAR(500) NOT NULL,
  title      VARCHAR(300)     NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS media_files_idx_ref ON media_files (ref_type, ref_id);

CREATE INDEX IF NOT EXISTS media_files_idx_kind ON media_files (kind);

CREATE TABLE IF NOT EXISTS settings (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  key        VARCHAR(100) NOT NULL,
  value      TEXT             NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS books (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title       VARCHAR(400) NOT NULL,
  description TEXT             NULL,
  cover_image VARCHAR(350)     NULL,
  pdf_file    VARCHAR(350)     NULL,
  word_file   VARCHAR(350)     NULL,
  downloads   INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS books_idx_created ON books (created_at);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS speaker VARCHAR(200);

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS video_file TEXT;

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS pdf_file TEXT;

ALTER TABLE media_files ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

INSERT INTO settings (key, value) VALUES
('site_name',        'مدرسه علمیه جامعه‌الهدی'),
('site_slogan',      'علم، معرفت و تهذیب در پرتو قرآن و عترت'),
('site_email',       'hajiahmads299@gmail.com'),
('address',          'کابل، افغانستان'),
('phone',            '0798228441'),
('email',            'hajiahmads299@gmail.com'),
('social_telegram',  ''),
('social_youtube',   ''),
('social_instagram', '') ON CONFLICT DO NOTHING;

INSERT INTO categories (name, slug, description, post_type, sort_order) VALUES
('فقه و اصول',         'fiqh-osul',         'مباحث فقه و اصول فقه',              'all',      1),
('تفسیر و قرآن',       'tafsir-quran',       'تفسیر آیات قرآن کریم',              'all',      2),
('فلسفه و کلام',       'falsafe-kalam',      'فلسفه اسلامی و علم کلام',           'all',      3),
('اخلاق و معرفت',      'akhlaq-marefat',     'اخلاق اسلامی و معرفت دینی',         'all',      4),
('اخبار مدرسه',        'akhbar-madrasa',     'اخبار و رویدادهای مدرسه',           'news',     5),
('مقالات علمی',        'maqalat-elmi',       'مقالات علمی و پژوهشی',              'article',  6),
('برنامه‌های تابستانه','baraname-tabestane', 'دوره‌های تابستانه',                 'program',  7),
('فعالیت‌های مذهبی',   'faaliyet-mazhabie',  'مراسم، محافل و فعالیت‌های مذهبی',  'religious',8) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS app_sessions (
 id VARCHAR(128) PRIMARY KEY, data TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS app_sessions_expiry ON app_sessions(expires_at);
CREATE TABLE IF NOT EXISTS login_limits (
 key VARCHAR(64) PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, expires_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS stored_files (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 file_key TEXT NOT NULL UNIQUE, url TEXT NOT NULL UNIQUE, mime TEXT NOT NULL,
 size BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contact_rate_limit ON contact_messages(ip_address,created_at);
CREATE TABLE IF NOT EXISTS storage_deletions (reference TEXT PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS posts_public_listing ON posts(status,post_type,published_at DESC);
CREATE INDEX IF NOT EXISTS lessons_public_listing ON lessons(status,created_at DESC);
CREATE INDEX IF NOT EXISTS media_ordered_reference ON media_files(ref_type,ref_id,kind,sort_order,id);
COMMIT;
