<?php
/**
 * sitemap.php — canonical XML sitemap for Google and other crawlers.
 *
 * Rules:
 * - Only public, indexable URLs are included.
 * - Every content URL is produced from the same route registry/canonical
 *   helpers used by page metadata. The sitemap therefore cannot drift from the
 *   canonical when the site uses either pretty paths or supported query URLs.
 * - Published content is discovered straight from the database, so anything
 *   published from the admin panel appears here automatically.
 * - Drafts, private areas (admin, login, register, account, profile, search,
 *   installer, migration, storage endpoints) and duplicate/legacy spellings
 *   are excluded by an explicit guard — not by hoping they are not generated.
 * - Topic paths preserve the parent/child hierarchy.
 */
require_once __DIR__ . '/includes/functions.php';

$origin = SITE_URL && filter_var(SITE_URL, FILTER_VALIDATE_URL)
    ? rtrim(SITE_URL, '/')
    : 'https://jametulhoda.vercel.app';

header('Content-Type: application/xml; charset=utf-8');
header('Cache-Control: public, max-age=900, stale-while-revalidate=3600');

/**
 * Path prefixes that must never appear in a public sitemap.
 * Matched against the path portion (without query string) of every candidate.
 */
$sitemapDenyPrefixes = [
    '/admin', '/login', '/logout', '/register', '/account', '/profile',
    '/password-change', '/search', '/install', '/php/install', '/php/migrate',
    '/migrate', '/config', '/includes', '/database', '/bin', '/storage',
    '/tests', '/uploads', '/api',
];

/**
 * Reject any URL that is not a plain public page of this origin.
 * http:// is accepted because a local/dev origin uses it; production always
 * configures SITE_URL as https, so a published sitemap is https throughout.
 */
$sitemapAllowed = static function (string $url) use ($origin, $sitemapDenyPrefixes): bool {
    if (!preg_match('~^https?://~i', $url)) return false;
    $parts = parse_url($url);
    if (!is_array($parts)) return false;
    $path = $parts['path'] ?? '';
    if (!is_string($path) || $path === '') return false;
    if (!str_starts_with($url, $origin . '/') && $url !== $origin . '/') return false;
    foreach ($sitemapDenyPrefixes as $prefix) {
        if ($path === $prefix || str_starts_with($path, $prefix . '/')) return false;
    }

    // Query mode is the safe default on hosts without rewrite support. Keep
    // only explicit, public routes generated by url(); never turn arbitrary or
    // private query parameters into crawlable sitemap entries.
    $queryString = (string)($parts['query'] ?? '');
    if ($queryString !== '') {
        parse_str($queryString, $query);
        $route = $query['p'] ?? null;
        $publicQueryRoutes = [
            'news', 'articles', 'reports', 'research', 'books', 'lessons', 'topics',
            'media', 'videos', 'audios', 'speeches', 'events', 'programs',
            'announcements', 'religious-activities', 'qa', 'about', 'contact',
            'article', 'report', 'event', 'announcement', 'program', 'religious', 'speech',
            'post', 'book', 'lesson', 'topic', 'category', 'video', 'audio',
        ];
        if (!is_string($route) || !in_array($route, $publicQueryRoutes, true)) return false;
        if (array_diff(array_keys($query), ['p', 'slug', 'id']) !== []) return false;
        if (isset($query['slug']) && (!is_string($query['slug']) || trim($query['slug']) === '')) return false;
        if (isset($query['id']) && (!is_string($query['id']) || !ctype_digit($query['id']) || (int)$query['id'] < 1)) return false;
    }
    return true;
};

$entries = [];
$seen = [];

/** Add an already-generated URL (the same string a page would render). */
$addUrl = static function (string $relative, ?string $lastmod = null) use (&$entries, &$seen, $sitemapAllowed): void {
    $loc = jhd_absolute_url($relative);
    if (!$sitemapAllowed($loc)) return;

    // Normalise trailing slashes and fragments while preserving an approved
    // Query-mode route: its p/slug/id parameters are part of the canonical URL.
    // Keep the port; dropping it would rewrite a non-default-port dev origin.
    $parts = parse_url($loc);
    if (!is_array($parts) || empty($parts['scheme']) || empty($parts['host'])) return;
    $path = rtrim((string)($parts['path'] ?? '/'), '/');
    if ($path === '') $path = '/';
    $port = isset($parts['port']) ? ':' . $parts['port'] : '';
    $query = (string)($parts['query'] ?? '');
    $loc = $parts['scheme'] . '://' . $parts['host'] . $port . $path . ($query !== '' ? '?' . $query : '');

    if (isset($seen[$loc])) return;
    $seen[$loc] = true;

    $entry = ['loc' => $loc];
    if ($lastmod) {
        $ts = strtotime((string)$lastmod);
        if ($ts !== false) $entry['lastmod'] = gmdate('Y-m-d', $ts);
    }
    $entries[] = $entry;
};

/** Add a listing/detail route through the central url() helper. */
$add = static function (string $route, array $params = [], ?string $lastmod = null) use ($addUrl): void {
    $addUrl($route === 'home' ? url() : url($route, $params), $lastmod);
};

/**
 * Public landing pages are included only when the page has real published
 * content. Static identity pages stay indexable; empty archives do not become
 * permanent sitemap URLs.
 */
$db = jhd_db();
$landingHasContent = [
    'home' => true,
    'about' => true,
    'contact' => true,
];

if ($db !== null) {
    try {
        $postCounts = $db->query("
            SELECT post_type, COUNT(*) AS total
            FROM posts
            WHERE status = 'published'
            GROUP BY post_type
        ")->fetchAll();
        foreach ($postCounts as $row) {
            $type = (string)($row['post_type'] ?? '');
            $landingHasContent[$type] = (int)$row['total'] > 0;
        }
        $eventCount = 0;
        foreach (['program', 'religious', 'announcement'] as $eventType) {
            $eventCount += (int)($landingHasContent[$eventType] ?? false);
        }
        $landingHasContent['events'] = $eventCount > 0;
        $landingHasContent['programs'] = (bool)($landingHasContent['program'] ?? false);
        $landingHasContent['announcements'] = (bool)($landingHasContent['announcement'] ?? false);
        $landingHasContent['religious-activities'] = (bool)($landingHasContent['religious'] ?? false);
        $landingHasContent['news'] = (bool)($landingHasContent['news'] ?? false);
        $landingHasContent['articles'] = (bool)($landingHasContent['article'] ?? false);
        $landingHasContent['research'] = (bool)($landingHasContent['research'] ?? false);
        $landingHasContent['reports'] = (bool)($landingHasContent['report'] ?? false);
        $landingHasContent['speeches'] = (bool)($landingHasContent['speech'] ?? false);
        $landingHasContent['qa'] = (bool)($landingHasContent['qa'] ?? false);

        $lessonCount = (int)$db->query("SELECT COUNT(*) FROM lessons WHERE status = 'published'")->fetchColumn();
        $bookCount = (int)$db->query("SELECT COUNT(*) FROM books WHERE status = 'published'")->fetchColumn();
        $topicCount = (int)$db->query("SELECT COUNT(*) FROM topics WHERE is_active = 1 AND COALESCE(slug, '') <> ''")->fetchColumn();
        $mediaCounts = $db->query("
            SELECT m.kind, COUNT(DISTINCT m.id) AS total
            FROM media_files m
            LEFT JOIN posts p ON m.ref_type = 'post' AND p.id = m.ref_id
            LEFT JOIN lessons l ON m.ref_type = 'lesson' AND l.id = m.ref_id
            WHERE m.kind IN ('audio', 'video')
              AND (p.status = 'published' OR l.status = 'published')
            GROUP BY m.kind
        ")->fetchAll();

        $landingHasContent['lessons'] = $lessonCount > 0;
        $landingHasContent['books'] = $bookCount > 0;
        $landingHasContent['topics'] = $topicCount > 0;
        $landingHasContent['media'] = false;
        $landingHasContent['videos'] = false;
        $landingHasContent['audios'] = false;
        foreach ($mediaCounts as $row) {
            $kind = ($row['kind'] ?? '') === 'audio' ? 'audios' : 'videos';
            $has = (int)($row['total'] ?? 0) > 0;
            $landingHasContent[$kind] = $has;
            if ($has) $landingHasContent['media'] = true;
        }
    } catch (Throwable $e) {
        error_log('sitemap landing counts failed: ' . get_class($e));
    }
}

/**
 * Search and authentication pages are intentionally absent.
 */
foreach ([
    'home',
    'news',
    'articles',
    'reports',
    'books',
    'lessons',
    'topics',
    'media',
    'videos',
    'audios',
    'speeches',
    'events',
    'programs',
    'announcements',
    'religious-activities',
    'qa',
    'about',
    'contact',
] as $route) {
    if ($route !== 'home' && $route !== 'about' && $route !== 'contact' && !($landingHasContent[$route] ?? false)) {
        continue;
    }
    $add($route);
}

if ($db !== null) {
    // ── Topics: build full parent/child slug paths in memory, avoiding N+1 DB queries.
    try {
        $rows = $db->query("
            SELECT id, parent_id, slug
            FROM topics
            WHERE is_active = 1
              AND COALESCE(slug, '') <> ''
            ORDER BY id
            LIMIT 50000
        ")->fetchAll();

        $byId = [];
        foreach ($rows as $row) {
            $byId[(int)$row['id']] = [
                'parent_id' => (int)($row['parent_id'] ?? 0),
                'slug' => trim((string)$row['slug']),
            ];
        }

        $topicPath = static function (int $id, array $trail = []) use (&$topicPath, $byId): string {
            if (!isset($byId[$id]) || isset($trail[$id])) return '';
            $trail[$id] = true;

            $own = trim($byId[$id]['slug']);
            if ($own === '') return '';

            $parent = (int)$byId[$id]['parent_id'];
            if ($parent > 0 && isset($byId[$parent])) {
                $parentPath = $topicPath($parent, $trail);
                if ($parentPath !== '') return $parentPath . '/' . $own;
            }
            return $own;
        };

        foreach ($byId as $id => $_row) {
            $slugPath = $topicPath((int)$id);
            if ($slugPath !== '') $add('topic', ['slug' => $slugPath]);
        }
    } catch (Throwable $e) {
        error_log('sitemap topics failed: ' . get_class($e));
    }

    // ── Published posts: one canonical detail URL per published post.
    //     postUrl() owns the post_type → route mapping and honors the configured
    //     URL mode, matching the detail page's canonical, redirects and cards.
    try {
        $stmt = $db->query("
            SELECT id, slug, post_type,
                   COALESCE(updated_at, published_at, created_at) AS lastmod
            FROM posts
            WHERE status = 'published'
              AND COALESCE(slug, '') <> ''
            ORDER BY COALESCE(updated_at, published_at, created_at) DESC, id DESC
            LIMIT 50000
        ");

        foreach ($stmt->fetchAll() as $row) {
            $addUrl(postUrl($row), $row['lastmod'] ?? null);
        }
    } catch (Throwable $e) {
        error_log('sitemap posts failed: ' . get_class($e));
    }

    // ── Published lessons.
    try {
        $stmt = $db->query("
            SELECT id, slug, COALESCE(updated_at, created_at) AS lastmod
            FROM lessons
            WHERE status = 'published'
              AND COALESCE(slug, '') <> ''
            ORDER BY COALESCE(updated_at, created_at) DESC, id DESC
            LIMIT 50000
        ");
        foreach ($stmt->fetchAll() as $row) {
            $addUrl(lessonUrl($row), $row['lastmod'] ?? null);
        }
    } catch (Throwable $e) {
        error_log('sitemap lessons failed: ' . get_class($e));
    }

    // ── Published books.
    try {
        $stmt = $db->query("
            SELECT id, slug, COALESCE(updated_at, created_at) AS lastmod
            FROM books
            WHERE status = 'published'
            ORDER BY COALESCE(updated_at, created_at) DESC, id DESC
            LIMIT 50000
        ");
        foreach ($stmt->fetchAll() as $row) {
            $addUrl(bookUrl($row), $row['lastmod'] ?? null);
        }
    } catch (Throwable $e) {
        error_log('sitemap books failed: ' . get_class($e));
    }

    // ── Active categories.
    try {
        $stmt = $db->query("
            SELECT slug
            FROM categories
            WHERE COALESCE(slug, '') <> ''
            ORDER BY id
            LIMIT 50000
        ");
        foreach ($stmt->fetchAll() as $row) {
            $addUrl(categoryUrl((string)$row['slug']));
        }
    } catch (Throwable $e) {
        error_log('sitemap categories failed: ' . get_class($e));
    }

    // ── Public audio/video detail pages attached to published content.
    try {
        $stmt = $db->query("
            SELECT DISTINCT m.id, m.kind, m.created_at
            FROM media_files m
            LEFT JOIN posts p
              ON m.ref_type = 'post' AND p.id = m.ref_id
            LEFT JOIN lessons l
              ON m.ref_type = 'lesson' AND l.id = m.ref_id
            WHERE m.kind IN ('audio', 'video')
              AND (p.status = 'published' OR l.status = 'published')
            ORDER BY m.id
            LIMIT 50000
        ");

        foreach ($stmt->fetchAll() as $row) {
            $kind = $row['kind'] === 'audio' ? 'audio' : 'video';
            $addUrl(mediaUrl($kind, (int)$row['id']), $row['created_at'] ?? null);
        }
    } catch (Throwable $e) {
        error_log('sitemap media failed: ' . get_class($e));
    }
}

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

foreach ($entries as $entry) {
    echo "  <url>\n";
    echo '    <loc>' . htmlspecialchars($entry['loc'], ENT_XML1 | ENT_QUOTES, 'UTF-8') . "</loc>\n";
    if (!empty($entry['lastmod'])) {
        echo '    <lastmod>' . htmlspecialchars($entry['lastmod'], ENT_XML1 | ENT_QUOTES, 'UTF-8') . "</lastmod>\n";
    }
    echo "  </url>\n";
}

echo "</urlset>\n";
