<?php
putenv('SESSION_DRIVER=files');
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/media.php';
require_once __DIR__ . '/../includes/auth.php';
$checks=0;
putenv('JHD_EMPTY_TEST=');
function check(bool $ok,string $label): void { global $checks; if(!$ok)throw new RuntimeException($label);$checks++; }
check(env_value('JHD_EMPTY_TEST','default')==='default','empty environment uses safe defaults');
check(siteUrl('news')===(JHD_PRETTY_URLS ? BASE_PATH.'/news' : BASE_PATH.'/index.php?p=news'),'clean public URL');
check(siteUrl('admin/users')===(JHD_PRETTY_URLS ? BASE_PATH.'/admin/users' : BASE_PATH.'/admin/users/index.php'),'clean admin URL');
check(siteUrl('login')===(JHD_PRETTY_URLS ? BASE_PATH.'/login' : BASE_PATH.'/index.php?p=login'),'public login URL');
check(siteUrl('admin/login')===BASE_PATH.'/admin/login','admin login URL');
check(siteUrl('')=== (BASE_PATH==='' ? '/' : BASE_PATH.'/'),'home URL is root-relative');
check(siteUrl('//evil.example')==='','protocol relative URL rejected');
check(siteUrl("javascript:alert(1)")==='','unsafe scheme rejected');
check(siteUrl("news\r\nX-Test:bad")==='','header injection rejected');
check(storageKey('../config/config.php')==='','traversal rejected');
check(storageKey('uploads/../secret.pdf')==='','upload traversal rejected');
check(storageKey('https://untrusted.example/file.pdf')==='','foreign storage rejected');
check(storageKey('uploads/posts/test.jpg')==='posts/test.jpg','legacy key supported');
check(storageKey('assets/img/logo.jpg')==='', 'assets are not uploads');
check(storageKey('videos/clip.mp4')==='videos/clip.mp4','videos folder supported');
check(storageKey('audios/clip.mp3')==='audios/clip.mp3','audios folder supported');
check(storageKey('video/legacy.mp4')==='video/legacy.mp4','legacy video folder still resolves');
check(storageKey('audio/legacy.mp3')==='audio/legacy.mp3','legacy audio folder still resolves');
check(storageKey('assets/images/logo.jpg')==='', 'legacy asset path is not an upload');
check(storageKey('posts/shell.php')==='','executable rejected');
check(validateUpload(__DIR__.'/fixtures/image.png','image')['mime']==='image/png','image content inspected');
check(validateUpload(__FILE__,'image')===null,'PHP disguised as image rejected');
check(validateUpload(__FILE__,'pdf')===null,'PHP disguised as PDF rejected');
check(validateUpload(__DIR__.'/fixtures/audio.mp3','audio')['extension']==='mp3','MP3 content');
check(validateUpload(__DIR__.'/fixtures/video.mp4','video')['extension']==='mp4','MP4 content');
$html=safeRichText('<p onclick="evil()">Hello <strong>world</strong></p><script>evil()</script><a href="javascript:alert(1)">x</a><img src="x" onerror="evil()"><svg onload="evil()"/>');
check(!str_contains($html,'evil()') && !str_contains($html,'javascript:') && !str_contains($html,'<svg'),'rich text XSS');
check(str_contains($html,'<strong>world</strong>'),'safe formatting retained');
check(persianDate('2024-03-20')==='1 فروردین 1403','Jalali new year');
check(persianDate('2026-09-20')==='29 شهریور 1405','Jalali current date');
$vercelBefore=getenv('VERCEL'); putenv('VERCEL');
$_SERVER['REMOTE_ADDR']='192.0.2.1'; $_SERVER['HTTP_X_FORWARDED_FOR']='203.0.113.1';
check(clientIp()==='192.0.2.1','untrusted forwarded IP ignored');
putenv('VERCEL=1'); $_SERVER['HTTP_X_VERCEL_FORWARDED_FOR']='203.0.113.2';
check(clientIp()==='203.0.113.2','trusted platform client IP');
putenv($vercelBefore===false?'VERCEL':'VERCEL='.$vercelBefore);
unset($_SERVER['HTTP_X_FORWARDED_FOR'],$_SERVER['HTTP_X_VERCEL_FORWARDED_FOR']);
$token=generateCsrfToken();
check(verifyCsrfToken($token),'valid CSRF');
check(!verifyCsrfToken('bad'),'invalid CSRF');
check(strlen($token)===64,'CSRF entropy');
echo "$checks security checks passed\n";
