-- PostgreSQL 15+ / Neon. Apply using php bin/migrate.php, never from a web request.
-- JametulHoda Content-Centered Architecture v2 — topics, lesson collections, enhanced books

BEGIN;

-- Single identity table (see database/database.mysql.sql for the rationale).
CREATE TABLE IF NOT EXISTS users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  username   VARCHAR(80)      NULL,
  email      VARCHAR(180)     NULL,
  phone      VARCHAR(32)      NULL,
  phone_normalized VARCHAR(32) NULL,
  country    VARCHAR(80)      NOT NULL DEFAULT '',
  country_code VARCHAR(8)     NOT NULL DEFAULT '',
  password   VARCHAR(255)     NOT NULL,
  full_name  VARCHAR(120)     NOT NULL DEFAULT '',
  role       VARCHAR(30)      NOT NULL DEFAULT 'user',
  is_active  SMALLINT         NOT NULL DEFAULT 1,
  must_change_password SMALLINT NOT NULL DEFAULT 0,
  agreed_terms SMALLINT       NOT NULL DEFAULT 0,
  avatar     VARCHAR(350)     NULL,
  last_login TIMESTAMPTZ      NULL,
  created_at TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  auth_version INT            NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE (username),
  UNIQUE (email),
  UNIQUE (phone_normalized)
);

CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(120) NOT NULL,
  slug        VARCHAR(160) NOT NULL,
  description TEXT             NULL,
  post_type   VARCHAR(30)  NOT NULL DEFAULT 'all',
  sort_order  INT          NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);

-- ── Topics: hierarchical, dynamic, core of site ──
CREATE TABLE IF NOT EXISTS topics (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  parent_id   INTEGER REFERENCES topics(id) ON DELETE SET NULL,
  name        VARCHAR(150) NOT NULL,
  slug        VARCHAR(200) NOT NULL,
  description TEXT,
  intro       TEXT,
  cover_image VARCHAR(500),
  sort_order  INT NOT NULL DEFAULT 0,
  is_active   SMALLINT NOT NULL DEFAULT 1,
  is_featured SMALLINT NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS topics_parent_idx ON topics(parent_id);
CREATE INDEX IF NOT EXISTS topics_active_sort ON topics(is_active, sort_order, id);
CREATE INDEX IF NOT EXISTS topics_featured ON topics(is_featured) WHERE is_featured=1;

CREATE TABLE IF NOT EXISTS posts (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title           VARCHAR(400)     NOT NULL,
  slug            VARCHAR(450)     NOT NULL,
  summary         TEXT                 NULL,
  content         TEXT             NULL,
  featured_image  VARCHAR(350)         NULL,
  featured_video  VARCHAR(500)         NULL,
  post_type       VARCHAR(30) NOT NULL DEFAULT 'news' CHECK (post_type IN ('news','article','research','report','announcement','speech','program','religious','qa','book_note')),
  page_section    VARCHAR(300)     NOT NULL DEFAULT 'home,news',
  category_id     INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  author_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status          VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('published','draft')),
  is_featured     SMALLINT       NOT NULL DEFAULT 0,
  published_at    TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS posts_idx_status_type ON posts (status, post_type);
CREATE INDEX IF NOT EXISTS posts_idx_category ON posts (category_id);
CREATE INDEX IF NOT EXISTS posts_idx_published ON posts (published_at);

CREATE TABLE IF NOT EXISTS post_images (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_id    INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  image_path VARCHAR(350) NOT NULL,
  alt_text   VARCHAR(200)     NULL,
  sort_order INTEGER     NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS post_images_idx_post ON post_images (post_id);
CREATE INDEX IF NOT EXISTS post_images_idx_order ON post_images (post_id, sort_order, id);
-- Ordered gallery support for existing installations (idempotent).
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

-- Junction: posts <-> topics (many-to-many)
CREATE TABLE IF NOT EXISTS post_topics (
  post_id  INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, topic_id)
);
CREATE INDEX IF NOT EXISTS post_topics_topic_idx ON post_topics(topic_id);

-- Lesson collections & volumes (content-centered)
CREATE TABLE IF NOT EXISTS lesson_collections (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title       VARCHAR(300) NOT NULL,
  slug        VARCHAR(300) NOT NULL,
  description TEXT,
  cover_image VARCHAR(500),
  sort_order  INT NOT NULL DEFAULT 0,
  is_active   SMALLINT NOT NULL DEFAULT 1,
  is_featured SMALLINT NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS lesson_collections_active_sort ON lesson_collections(is_active, sort_order);

CREATE TABLE IF NOT EXISTS lesson_volumes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
  collection_id INTEGER NOT NULL REFERENCES lesson_collections(id) ON DELETE CASCADE,
  title         VARCHAR(300) NOT NULL,
  slug          VARCHAR(300) NOT NULL,
  description   TEXT,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (collection_id, slug)
);
CREATE INDEX IF NOT EXISTS lesson_volumes_collection_sort ON lesson_volumes(collection_id, sort_order);

CREATE TABLE IF NOT EXISTS lessons (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(400) NOT NULL,
  slug           VARCHAR(450) NOT NULL,
  subject        VARCHAR(150)     NULL,
  teacher        VARCHAR(150)     NULL,
  content        TEXT         NULL,
  summary        TEXT             NULL,
  audio_file     VARCHAR(350)     NULL,
  featured_image VARCHAR(350)     NULL,
  level          VARCHAR(30) DEFAULT 'beginner',
  status         VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('published','draft')),
  page_section   VARCHAR(255) NOT NULL DEFAULT 'home',
  sort_order     INT          NOT NULL DEFAULT 0,
  lesson_number  INT,
  collection_id  INTEGER REFERENCES lesson_collections(id) ON DELETE SET NULL,
  volume_id      INTEGER REFERENCES lesson_volumes(id) ON DELETE SET NULL,
  is_featured    SMALLINT NOT NULL DEFAULT 0,
  created_by     INTEGER     NULL,
  created_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS lessons_idx_status ON lessons (status);
CREATE INDEX IF NOT EXISTS lessons_idx_collection ON lessons(collection_id, volume_id, lesson_number);
CREATE INDEX IF NOT EXISTS lessons_featured ON lessons(is_featured) WHERE is_featured=1;

-- Junction: lessons <-> topics
CREATE TABLE IF NOT EXISTS lesson_topics (
  lesson_id INTEGER NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  topic_id  INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  PRIMARY KEY (lesson_id, topic_id)
);
CREATE INDEX IF NOT EXISTS lesson_topics_topic_idx ON lesson_topics(topic_id);

CREATE TABLE IF NOT EXISTS contact_messages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name       VARCHAR(200) NOT NULL,
  email      VARCHAR(200)     NULL,
  phone      VARCHAR(50)      NULL,
  subject    VARCHAR(300)     NULL,
  message    TEXT         NOT NULL,
  ip_address VARCHAR(45)      NULL,
  is_read    SMALLINT   NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS contact_messages_idx_is_read ON contact_messages (is_read);
CREATE INDEX IF NOT EXISTS contact_messages_idx_created ON contact_messages (created_at);

CREATE TABLE IF NOT EXISTS media_files (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  ref_type   VARCHAR(30)  NOT NULL DEFAULT 'post',
  ref_id     INTEGER NOT NULL,
  kind       VARCHAR(30) NOT NULL DEFAULT 'image',
  file_path  VARCHAR(500) NOT NULL,
  title      VARCHAR(300)     NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS media_files_idx_ref ON media_files (ref_type, ref_id);
CREATE INDEX IF NOT EXISTS media_files_idx_kind ON media_files (kind);

-- setting_key: the column must not be named "key" because MySQL reserves it.
-- Both schemas use the same name so application SQL stays driver-neutral.
CREATE TABLE IF NOT EXISTS settings (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  setting_key VARCHAR(100) NOT NULL,
  value      TEXT             NULL,
  created_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (setting_key)
);
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='settings' AND column_name='key') THEN
    ALTER TABLE settings RENAME COLUMN key TO setting_key;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS books (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title       VARCHAR(400) NOT NULL,
  description TEXT             NULL,
  cover_image VARCHAR(350)     NULL,
  pdf_file    VARCHAR(350)     NULL,
  word_file   VARCHAR(350)     NULL,
  author      VARCHAR(250),
  translator  VARCHAR(250),
  publisher   VARCHAR(250),
  publish_year VARCHAR(20),
  pages       INTEGER,
  toc         TEXT,
  is_featured SMALLINT NOT NULL DEFAULT 0,
  sort_order  INT NOT NULL DEFAULT 0,
  status      VARCHAR(30) NOT NULL DEFAULT 'published' CHECK (status IN ('published','draft')),
  downloads   INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS books_idx_created ON books (created_at);
CREATE INDEX IF NOT EXISTS books_idx_featured ON books(is_featured) WHERE is_featured=1;

-- Junction: books <-> topics
CREATE TABLE IF NOT EXISTS book_topics (
  book_id  INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  PRIMARY KEY (book_id, topic_id)
);
CREATE INDEX IF NOT EXISTS book_topics_topic_idx ON book_topics(topic_id);

-- Site banners / special announcements (dynamic hero banner)
CREATE TABLE IF NOT EXISTS site_banners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  title      VARCHAR(300) NOT NULL,
  content    TEXT,
  link_url   VARCHAR(500),
  link_text  VARCHAR(100),
  banner_type VARCHAR(30) NOT NULL DEFAULT 'info',
  is_active  SMALLINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  starts_at  TIMESTAMPTZ,
  ends_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS site_banners_active ON site_banners(is_active, sort_order);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS speaker VARCHAR(200);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS video_file TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS pdf_file TEXT;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

-- Cleanup legacy columns if they exist (idempotent)
ALTER TABLE posts DROP COLUMN IF EXISTS views;
ALTER TABLE lessons DROP COLUMN IF EXISTS views;
DROP TABLE IF EXISTS post_likes;

-- Backfill new books columns if upgrading from old schema
ALTER TABLE books ADD COLUMN IF NOT EXISTS author VARCHAR(250);
ALTER TABLE books ADD COLUMN IF NOT EXISTS translator VARCHAR(250);
ALTER TABLE books ADD COLUMN IF NOT EXISTS publisher VARCHAR(250);
ALTER TABLE books ADD COLUMN IF NOT EXISTS publish_year VARCHAR(20);
ALTER TABLE books ADD COLUMN IF NOT EXISTS pages INTEGER;
ALTER TABLE books ADD COLUMN IF NOT EXISTS toc TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS is_featured SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'published';

-- Lesson hierarchy columns if upgrading
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS lesson_number INT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS collection_id INTEGER REFERENCES lesson_collections(id) ON DELETE SET NULL;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS volume_id INTEGER REFERENCES lesson_volumes(id) ON DELETE SET NULL;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS is_featured SMALLINT NOT NULL DEFAULT 0;


-- Ensure book slug exists for SEO friendly URLs
ALTER TABLE books ADD COLUMN IF NOT EXISTS slug VARCHAR(300);
CREATE UNIQUE INDEX IF NOT EXISTS books_slug_unique ON books(slug) WHERE slug IS NOT NULL AND slug <> '';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS sources TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS sources TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS author_name VARCHAR(250);
-- Featured banners (dynamic special announcement)
CREATE TABLE IF NOT EXISTS featured_banners (
  id SERIAL PRIMARY KEY,
  title VARCHAR(300) NOT NULL,
  description TEXT,
  image VARCHAR(500),
  link_url VARCHAR(500),
  button_text VARCHAR(100),
  is_active SMALLINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO settings (setting_key, value) VALUES
('site_name',        'جامعة‌الهدی'),
('site_slogan',      'مرکز علمی، آموزشی و پژوهشی در پرتو قرآن و عترت'),
('site_email',       'hajiahmads299@gmail.com'),
('address',          'کابل، افغانستان'),
('phone',            '0798228441'),
('email',            'hajiahmads299@gmail.com'),
('social_telegram',  ''),
('social_youtube',   ''),
('social_instagram', '') ON CONFLICT DO NOTHING;

INSERT INTO categories (name, slug, description, post_type, sort_order) VALUES
('فقه و اصول',         'fiqh-osul',         'مباحث فقه و اصول فقه',              'all',      1),
('تفسیر و قرآن',       'tafsir-quran',       'تفسیر آیات قرآن کریم',              'all',      2),
('فلسفه و کلام',       'falsafe-kalam',      'فلسفه اسلامی و علم کلام',           'all',      3),
('اخلاق و معرفت',      'akhlaq-marefat',     'اخلاق اسلامی و معرفت دینی',         'all',      4),
('اخبار مدرسه',        'akhbar-madrasa',     'اخبار و رویدادهای مدرسه',           'news',     5),
('مقالات علمی',        'maqalat-elmi',       'مقالات علمی و پژوهشی',              'article',  6),
('برنامه‌های تابستانه','baraname-tabestane', 'دوره‌های تابستانه',                 'program',  7),
('فعالیت‌های مذهبی',   'faaliyet-mazhabie',  'مراسم، محافل و فعالیت‌های مذهبی',  'religious',8) ON CONFLICT DO NOTHING;

-- Seed core topics as content backbone (migrated / canonical)
INSERT INTO topics (name, slug, description, intro, sort_order, is_featured) VALUES
('مهدویت', 'mahdaviat', 'مباحث مرتبط با مهدویت و امام زمان (عج)', 'بررسی عقیده مهدویت، انتظار و ظهور در منابع اسلامی', 1, 1),
('امام حسین (ع)', 'imam-hussein', 'زندگی، قیام و پیام‌های عاشورا', 'شناخت نهضت حسینی و درس‌های عاشورا برای جامعه امروز', 2, 1),
('قرآن و حدیث', 'quran-hadith', 'علوم قرآن، تفسیر، حدیث و نهج‌البلاغه', 'آشنایی با معارف قرآنی و روایی اهل بیت', 3, 1),
('فقه و اصول', 'fiqh-osool', 'احکام، فقه استدلالی و اصول فقه', 'مبانی اجتهاد و استنباط احکام شرعی', 4, 0),
('اخلاق و تربیت', 'akhlaq-tarbiat', 'اخلاق اسلامی و سیر و سلوک', 'تهذیب نفس و پرورش معنوی بر اساس قرآن و عترت', 5, 0),
('تاریخ اسلام', 'tarikh-islam', 'سیره معصومین و تاریخ تشیع', 'بررسی تاریخی اسلام و نقش اهل بیت', 6, 0)
ON CONFLICT (slug) DO NOTHING;

-- Subtopics examples
INSERT INTO topics (parent_id, name, slug, description, sort_order) VALUES
((SELECT id FROM topics WHERE slug='mahdaviat' LIMIT 1), 'امام مهدی (عج)', 'imam-mahdi', 'شناخت حضرت مهدی (عج)', 1),
((SELECT id FROM topics WHERE slug='mahdaviat' LIMIT 1), 'غیبت', 'ghaybat', 'غیبت صغری و کبری', 2),
((SELECT id FROM topics WHERE slug='mahdaviat' LIMIT 1), 'ظهور', 'zohour', 'نشانه‌ها و شرایط ظهور', 3),
((SELECT id FROM topics WHERE slug='mahdaviat' LIMIT 1), 'انتظار', 'entezar', 'وظایف منتظران', 4),
((SELECT id FROM topics WHERE slug='imam-hussein' LIMIT 1), 'زندگی امام حسین (ع)', 'zendegi-imam-hussein', 'دوران زندگی و امامت', 1),
((SELECT id FROM topics WHERE slug='imam-hussein' LIMIT 1), 'قیام عاشورا', 'qiyam-ashura', 'تحلیل قیام عاشورا', 2),
((SELECT id FROM topics WHERE slug='imam-hussein' LIMIT 1), 'پیام‌های عاشورا', 'payam-ashura', 'درس‌ها و عبرت‌های عاشورا', 3),
((SELECT id FROM topics WHERE slug='quran-hadith' LIMIT 1), 'علوم قرآن', 'oloum-quran', 'مبانی علوم قرآنی', 1),
((SELECT id FROM topics WHERE slug='quran-hadith' LIMIT 1), 'تفسیر', 'tafsir', 'تفسیر آیات قرآن', 2),
((SELECT id FROM topics WHERE slug='quran-hadith' LIMIT 1), 'نهج‌البلاغه', 'nahjolbalaghe', 'شرح نهج‌البلاغه', 3)
ON CONFLICT (slug) DO NOTHING;

CREATE TABLE IF NOT EXISTS app_sessions (
 id VARCHAR(128) PRIMARY KEY, data TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS app_sessions_expiry ON app_sessions(expires_at);
CREATE TABLE IF NOT EXISTS login_limits (
 limit_key VARCHAR(64) PRIMARY KEY, attempts INTEGER NOT NULL DEFAULT 0, expires_at TIMESTAMPTZ NOT NULL
);
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='login_limits' AND column_name='key') THEN
    ALTER TABLE login_limits RENAME COLUMN key TO limit_key;
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS stored_files (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 file_key TEXT NOT NULL UNIQUE, url TEXT NOT NULL UNIQUE, mime TEXT NOT NULL,
 size BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS contact_rate_limit ON contact_messages(ip_address,created_at);
CREATE TABLE IF NOT EXISTS storage_deletions (reference TEXT PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE storage_deletions ADD COLUMN IF NOT EXISTS not_before TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE TABLE IF NOT EXISTS pending_uploads (
 reference TEXT PRIMARY KEY,
 not_before TIMESTAMPTZ NOT NULL DEFAULT (NOW()+INTERVAL '24 hours'),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pending_uploads_due ON pending_uploads(not_before);
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 1;
-- Legacy public accounts are migrated into `users` (role='user') by
-- includes/identity.php; the old table is renamed to members_migrated_v1.
ALTER TABLE post_topics ADD COLUMN IF NOT EXISTS is_primary SMALLINT NOT NULL DEFAULT 0;
INSERT INTO topics (name, slug, description, intro, sort_order, is_featured) VALUES
('حدیث', 'hadith', 'علوم حدیث و درایت', 'شناخت روایات اهل بیت', 7, 0),
('سیره', 'sireh', 'سیره پیامبر و اهل بیت', 'سبک زندگی معصومان', 8, 0),
('اندیشه اسلامی', 'andishe-islami', 'کلام، فلسفه و اندیشه معاصر', 'پرسش‌های بنیادین دین', 9, 0)
ON CONFLICT (slug) DO NOTHING;
CREATE INDEX IF NOT EXISTS posts_public_listing ON posts(status,post_type,published_at DESC);
CREATE INDEX IF NOT EXISTS lessons_public_listing ON lessons(status,created_at DESC);
CREATE INDEX IF NOT EXISTS media_ordered_reference ON media_files(ref_type,ref_id,kind,sort_order,id);

-- ═══════════════════════════════════════════════════════════════════════════
-- رسانهٔ شاخص چندگانه + شاخص‌های کارایی (نسخهٔ Design System یکپارچه)
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS is_featured SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS featured_order INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS post_images_featured ON post_images (post_id, is_featured, featured_order, id);
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS is_featured SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS featured_order INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS media_files_featured ON media_files (ref_type, ref_id, kind, is_featured, featured_order, id);
CREATE INDEX IF NOT EXISTS posts_slug_idx ON posts (slug);
CREATE INDEX IF NOT EXISTS posts_featured_listing ON posts (status, is_featured, published_at);
CREATE INDEX IF NOT EXISTS topics_slug_idx ON topics (slug);
CREATE INDEX IF NOT EXISTS books_slug_idx ON books (slug);
CREATE INDEX IF NOT EXISTS lessons_slug_idx ON lessons (slug);
CREATE INDEX IF NOT EXISTS post_topics_post_idx ON post_topics (post_id, topic_id);

-- Opaque, revocable native API sessions. Raw access/refresh tokens are never stored.
CREATE TABLE IF NOT EXISTS mobile_api_tokens (
    token_hash CHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    auth_version INT NOT NULL,
    family_id CHAR(32) NOT NULL,
    token_type VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NULL,
    last_used_at TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS mobile_api_tokens_user_idx ON mobile_api_tokens(user_id);
CREATE INDEX IF NOT EXISTS mobile_api_tokens_family_idx ON mobile_api_tokens(family_id);
CREATE INDEX IF NOT EXISTS mobile_api_tokens_expiry_idx ON mobile_api_tokens(expires_at);
COMMIT;
