<?php
/** Edit a lesson without losing its course/volume/file relationships. */
$adminTitle = 'ویرایش درس';
require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../../includes/media.php';
require_once __DIR__ . '/../../includes/post-gallery.php';

$id=(int)($_GET['id'] ?? 0); $db=getDB(); $stmt=$db->prepare('SELECT * FROM lessons WHERE id=? LIMIT 1');$stmt->execute([$id]);$lesson=$stmt->fetch();
if(!$lesson){$_SESSION['flash_msg']='درس یافت نشد.';$_SESSION['flash_type']='danger';redirect(siteUrl('admin/lessons/'));}
$error=''; $collections=getLessonCollections(['active'=>null]); $volumes=[];foreach($collections as $collection)foreach(getLessonVolumes((int)$collection['id']) as $volume)$volumes[]=['collection'=>$collection,'volume'=>$volume];
if($_SERVER['REQUEST_METHOD']==='POST'){
 beginContentUploadScope();
 if(!verifyCsrfToken($_POST[CSRF_TOKEN_NAME] ?? ''))$error='خطای امنیتی.';
 else{
  $title=trim((string)($_POST['title']??'')); if($title==='')$error='عنوان درس الزامی است.';
  if($error==='')try{
   $collectionId=(int)($_POST['collection_id']??0);$volumeId=(int)($_POST['volume_id']??0);if($volumeId){$volume=getLessonVolumeById($volumeId);if(!$volume||($collectionId&&(int)$volume['collection_id']!==$collectionId))throw new RuntimeException('جلد انتخاب‌شده با دوره انتخابی هماهنگ نیست.');$collectionId=(int)$volume['collection_id'];}
   $context=['collection_id'=>$collectionId,'volume_id'=>$volumeId];
   $image=(string)($lesson['featured_image']??'');$audio=(string)($lesson['audio_file']??'');$video=(string)($lesson['video_file']??'');$pdf=(string)($lesson['pdf_file']??'');
   foreach([['remove_image','image'],['remove_audio','audio'],['remove_video','video'],['remove_pdf','pdf']] as [$flag,$field]) if(!empty($_POST[$flag])&&$$field){scheduleFileDeletion($$field);$$field='';}
   if((($_FILES['featured_image']['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE)){if ($_FILES['featured_image']['error'] !== UPLOAD_ERR_OK) throw new RuntimeException(jhd_upload_error_message((int)$_FILES['featured_image']['error']));$new=uploadContentImage($_FILES['featured_image'],'lesson',$id,$context);if(!$new)throw new RuntimeException('تصویر درس معتبر نیست.');if($image)scheduleFileDeletion($image);$image=$new;}
   if((($_FILES['audio_file']['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE)){if ($_FILES['audio_file']['error'] !== UPLOAD_ERR_OK) throw new RuntimeException(jhd_upload_error_message((int)$_FILES['audio_file']['error']));$new=uploadContentAudio($_FILES['audio_file'],'lesson',$id,$context);if(!$new)throw new RuntimeException('فایل صوتی معتبر نیست.');if($audio)scheduleFileDeletion($audio);$audio=$new;}
   if((($_FILES['video_file']['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE)){if ($_FILES['video_file']['error'] !== UPLOAD_ERR_OK) throw new RuntimeException(jhd_upload_error_message((int)$_FILES['video_file']['error']));$new=uploadContentVideo($_FILES['video_file'],'lesson',$id,$context);if(!$new)throw new RuntimeException('ویدیو معتبر نیست.');if($video)scheduleFileDeletion($video);$video=$new;}
   if((($_FILES['pdf_file']['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_NO_FILE)){if ($_FILES['pdf_file']['error'] !== UPLOAD_ERR_OK) throw new RuntimeException(jhd_upload_error_message((int)$_FILES['pdf_file']['error']));$new=uploadContentDocument($_FILES['pdf_file'],'lesson',$id,'pdf',$context);if(!$new)throw new RuntimeException('PDF معتبر نیست.');if($pdf)scheduleFileDeletion($pdf);$pdf=$new;}
   requireMediaUploads(
    handleMediaUploads('lesson', $id, $_FILES['attachment_files'] ?? [], 'document', $context),
    handleMediaUploads('lesson', $id, $_FILES['audio_files'] ?? [], 'audio', $context),
    handleMediaUploads('lesson', $id, $_FILES['video_files'] ?? [], 'video', $context)
   );
   $status=in_array($_POST['status']??'', ['published','draft'],true)?$_POST['status']:'draft';$level=in_array($_POST['level']??'', ['beginner','intermediate','advanced'],true)?$_POST['level']:'beginner';$lessonNo=max(0,(int)($_POST['lesson_number']??0));
   $db->prepare('UPDATE lessons SET title=?,slug=?,subject=?,teacher=?,content=?,summary=?,sources=?,featured_image=?,audio_file=?,video_file=?,pdf_file=?,status=?,page_section=?,level=?,sort_order=?,lesson_number=?,collection_id=?,volume_id=?,updated_at=NOW() WHERE id=?')->execute([$title,uniqueSlug('lessons',$title,$id),trim((string)($_POST['subject']??''))?:null,trim((string)($_POST['teacher']??''))?:null,(string)($_POST['content']??'')?:null,trim((string)($_POST['summary']??''))?:null,trim((string)($_POST['sources']??''))?:null,$image?:null,$audio?:null,$video?:null,$pdf?:null,$status,'lessons',$level,(int)($_POST['sort_order']??0),$lessonNo?:null,$collectionId?:null,$volumeId?:null,$id]);
   syncPrimaryMediaFile('lesson',$id,'audio',$audio,$title);syncPrimaryMediaFile('lesson',$id,'video',$video,$title);setLessonTopics($id,validatedTopicIds((array)($_POST['topic_ids']??[])));foreach((array)($_POST['delete_attachment']??[])as$mediaId)deleteMediaFile((int)$mediaId,'lesson',$id);
   foreach (['document','audio','video'] as $kind) {
    $items = array_filter(getMediaFor('lesson', $id, $kind), static fn($m) => (int)$m['sort_order'] !== -1000000);
    $ids = array_values(array_map('intval', array_column($items, 'id')));
    $ranking = (array)($_POST['media_rank'][$kind] ?? []);
    if ($ids && $ranking) {
     usort($ids, static fn(int $a, int $b): int => ((int)($ranking[$a] ?? 999999) <=> (int)($ranking[$b] ?? 999999)) ?: ($a <=> $b));
     if (!setMediaOrder($id, $ids, $kind, 'lesson')) throw new RuntimeException('ترتیب فایل‌های درس ذخیره نشد.');
    }
   }
   $stmt->execute([$id]);$lesson=$stmt->fetch();$_SESSION['flash_msg']='درس و رسانه‌های وابسته به‌روزرسانی شدند.';$_SESSION['flash_type']='success';redirect(siteUrl('admin/lessons/edit?id='.$id));
  }catch(Throwable $e){error_log('lesson edit failed: '.get_class($e));$error=$e instanceof RuntimeException?$e->getMessage():'ذخیره تغییرات با خطا مواجه شد.';}
 }
}
$topicIds=getTopicIdsForLesson($id);$attachments=getMediaFor('lesson',$id,'document');$extraAudio=array_values(array_filter(getMediaFor('lesson',$id,'audio'),static fn($m)=>($m['file_path']??'')!==($lesson['audio_file']??'')));$extraVideo=array_values(array_filter(getMediaFor('lesson',$id,'video'),static fn($m)=>($m['file_path']??'')!==($lesson['video_file']??'')));$allTopics=getTopics();
function lessonFileControl(string $name,string $label,string $path,string $accept,string $remove): string { $html='<div class="col-md-3"><label class="form-label">'.sanitize($label).'</label>';if($path!=='')$html.='<a class="d-block small mb-2" target="_blank" rel="noopener noreferrer" href="'.sanitize(imgUrl($path)).'">فایل فعلی</a><label class="form-check small text-danger"><input class="form-check-input" type="checkbox" name="'.sanitize($remove).'" value="1"> حذف</label>';return $html.'<input class="form-control mt-2" type="file" name="'.sanitize($name).'" accept="'.sanitize($accept).'"></div>';}
?>
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h5 mb-0">ویرایش درس: <?=sanitize(mb_strimwidth($lesson['title'],0,45,'…'))?></h1><div class="d-flex gap-2"><a class="btn btn-outline-success btn-sm" target="_blank" rel="noopener noreferrer" href="<?=lessonUrl($lesson)?>">مشاهده</a><a class="btn btn-outline-secondary btn-sm" href="<?=siteUrl('admin/lessons/')?>">بازگشت</a></div></div><?php if($error):?><div class="alert alert-danger"><?=sanitize($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="admin-form"><?=csrfField()?><div class="row g-4"><div class="col-lg-8">
<section class="admin-card mb-4"><div class="admin-card-header">محتوای درس</div><div class="admin-card-body"><div class="mb-3"><label class="form-label">عنوان <span class="text-danger">*</span></label><input class="form-control" required name="title" value="<?=sanitize($lesson['title'])?>"></div><div class="row g-3"><div class="col-md-6"><label class="form-label">موضوع درسی</label><input class="form-control" name="subject" value="<?=sanitize((string)$lesson['subject'])?>"></div><div class="col-md-6"><label class="form-label">مدرس</label><input class="form-control" name="teacher" value="<?=sanitize((string)$lesson['teacher'])?>"></div></div><div class="mt-3"><label class="form-label">خلاصه</label><textarea class="form-control" rows="3" name="summary"><?=sanitize((string)$lesson['summary'])?></textarea></div><div class="mt-3"><label class="form-label">متن کامل</label><textarea class="form-control" rows="10" name="content"><?=htmlspecialchars((string)$lesson['content'],ENT_QUOTES,'UTF-8')?></textarea></div><div class="mt-3"><label class="form-label">منابع</label><textarea class="form-control" rows="4" name="sources"><?=sanitize((string)$lesson['sources'])?></textarea></div></div></section>
<section class="admin-card mb-4"><div class="admin-card-header">مسیر آموزشی و موضوعات</div><div class="admin-card-body"><div class="row g-3"><div class="col-md-5"><label class="form-label">دوره</label><select name="collection_id" class="form-select"><option value="">بدون دوره</option><?php foreach($collections as $collection):?><option value="<?= (int)$collection['id']?>" <?= (int)$lesson['collection_id']===(int)$collection['id']?'selected':''?>><?=sanitize($collection['title'])?></option><?php endforeach;?></select></div><div class="col-md-5"><label class="form-label">جلد / بخش</label><select name="volume_id" class="form-select"><option value="">بدون جلد</option><?php foreach($volumes as $entry):?><option value="<?= (int)$entry['volume']['id']?>" <?= (int)$lesson['volume_id']===(int)$entry['volume']['id']?'selected':''?>><?=sanitize($entry['collection']['title'].' — '.$entry['volume']['title'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">شماره</label><input class="form-control" min="1" type="number" name="lesson_number" value="<?= (int)$lesson['lesson_number']?>"></div></div><div class="mt-3"><input type="search" class="form-control form-control-sm mb-2" data-topic-filter data-topic-target="lessonTopicList" placeholder="جستجو در همهٔ موضوعات"><div id="lessonTopicList" style="max-height:240px;overflow:auto"><?php foreach($allTopics as $topic):?><label class="form-check <?= $topic['parent_id']?'ms-3':''?>"><input class="form-check-input" type="checkbox" name="topic_ids[]" value="<?= (int)$topic['id']?>" <?=in_array((int)$topic['id'],$topicIds,true)?'checked':''?>><span class="form-check-label"><?=sanitize($topic['name'])?></span></label><?php endforeach;?></div></div></div></section>
<section class="admin-card"><div class="admin-card-header">رسانه و فایل‌ها</div><div class="admin-card-body"><div class="row g-3"><?=lessonFileControl('featured_image','تصویر',(string)$lesson['featured_image'],'image/jpeg,image/png,image/gif,image/webp','remove_image')?><?=lessonFileControl('audio_file','صوت',(string)$lesson['audio_file'],'audio/*,.mp3,.ogg,.wav,.m4a','remove_audio')?><?=lessonFileControl('video_file','ویدیو',(string)$lesson['video_file'],'video/*,.mp4,.webm,.mov,.mkv','remove_video')?><?=lessonFileControl('pdf_file','PDF',(string)$lesson['pdf_file'],'application/pdf,.pdf','remove_pdf')?></div><hr><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">صوت‌های تکمیلی</label><input class="form-control" type="file" name="audio_files[]" accept="audio/*" multiple></div><div class="col-md-6"><label class="form-label">ویدیوهای تکمیلی</label><input class="form-control" type="file" name="video_files[]" accept="video/*" multiple></div></div><label class="form-label">فایل‌های تکمیلی</label><input class="form-control" type="file" multiple name="attachment_files[]" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"><?php foreach (['audio'=>$extraAudio,'video'=>$extraVideo] as $kind=>$items): ?><?php if($items):?><p class="small fw-bold mt-3"><?= $kind === 'audio' ? 'صوت‌ها' : 'ویدیوها' ?></p><ul class="list-group"><?php foreach($items as $file):?><li class="list-group-item d-flex flex-wrap align-items-center gap-2"><a href="<?=sanitize(imgUrl($file['file_path']))?>" target="_blank" rel="noopener"><?=sanitize($file['title'] ?: basename($file['file_path']))?></a><input type="number" class="form-control form-control-sm ms-auto" style="width:5rem" aria-label="ترتیب" name="media_rank[<?= $kind ?>][<?= (int)$file['id'] ?>]" value="<?= (int)$file['sort_order'] ?>"><label class="small text-danger"><input type="checkbox" name="delete_attachment[]" value="<?= (int)$file['id'] ?>"> حذف</label></li><?php endforeach;?></ul><?php endif;?><?php endforeach;?><?php if($attachments):?><ul class="list-group list-group-flush mt-3"><?php foreach($attachments as$file):?><li class="list-group-item d-flex justify-content-between gap-2"><a class="small text-truncate" target="_blank" rel="noopener noreferrer" href="<?=imgUrl($file['file_path'])?>"><?=sanitize($file['title']?:basename($file['file_path']))?></a><input type="number" class="form-control form-control-sm ms-auto" style="width:5rem" aria-label="ترتیب" name="media_rank[document][<?= (int)$file['id'] ?>]" value="<?= (int)$file['sort_order'] ?>"><label class="form-check small text-danger"><input class="form-check-input" type="checkbox" name="delete_attachment[]" value="<?= (int)$file['id']?>"> حذف</label></li><?php endforeach;?></ul><?php endif;?></div></section>
</div><aside class="col-lg-4"><section class="admin-card"><div class="admin-card-header">انتشار</div><div class="admin-card-body"><label class="form-label">وضعیت</label><select class="form-select mb-3" name="status"><option value="draft" <?=$lesson['status']==='draft'?'selected':''?>>پیش‌نویس</option><option value="published" <?=$lesson['status']==='published'?'selected':''?>>منتشرشده</option></select><label class="form-label">سطح</label><select class="form-select mb-3" name="level"><option value="beginner" <?=$lesson['level']==='beginner'?'selected':''?>>مبتدی</option><option value="intermediate" <?=$lesson['level']==='intermediate'?'selected':''?>>متوسط</option><option value="advanced" <?=$lesson['level']==='advanced'?'selected':''?>>پیشرفته</option></select><label class="form-label">ترتیب</label><input class="form-control mb-3" type="number" name="sort_order" value="<?= (int)$lesson['sort_order']?>"><button class="btn btn-success w-100">ذخیره تغییرات</button></div></section></aside></div></form>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
