<?php
/**
 * member-auth.php — احراز هویت کاربران عمومی (جدا از مدیران)
 *
 * Session keys: member_id / member_name / member_auth_version
 * Admin keys are never granted from this file. A member cannot reach /admin.
 */
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/functions.php';

function ensureMembersSchema(): void {
    static $done = false;
    if ($done) return;
    $done = true;
    try {
        $db = getDB();
        $driver = databaseDriver();
        if ($driver === 'mysql') {
            $db->exec("CREATE TABLE IF NOT EXISTS members (
                id INT AUTO_INCREMENT PRIMARY KEY,
                full_name VARCHAR(120) NOT NULL,
                country VARCHAR(80) NOT NULL DEFAULT '',
                country_code VARCHAR(8) NOT NULL DEFAULT '',
                phone VARCHAR(32) NOT NULL,
                phone_normalized VARCHAR(32) NOT NULL,
                email VARCHAR(180) NULL,
                password VARCHAR(255) NOT NULL,
                is_active SMALLINT NOT NULL DEFAULT 1,
                agreed_terms SMALLINT NOT NULL DEFAULT 0,
                auth_version INT NOT NULL DEFAULT 1,
                last_login DATETIME NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY members_phone_unique (phone_normalized),
                UNIQUE KEY members_email_unique (email)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        } elseif ($driver === 'sqlite') {
            $db->exec("CREATE TABLE IF NOT EXISTS members (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                full_name TEXT NOT NULL,
                country TEXT NOT NULL DEFAULT '',
                country_code TEXT NOT NULL DEFAULT '',
                phone TEXT NOT NULL,
                phone_normalized TEXT NOT NULL UNIQUE,
                email TEXT UNIQUE,
                password TEXT NOT NULL,
                is_active INTEGER NOT NULL DEFAULT 1,
                agreed_terms INTEGER NOT NULL DEFAULT 0,
                auth_version INTEGER NOT NULL DEFAULT 1,
                last_login TEXT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )");
        } else {
            $db->exec("CREATE TABLE IF NOT EXISTS members (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name VARCHAR(120) NOT NULL,
                country VARCHAR(80) NOT NULL DEFAULT '',
                country_code VARCHAR(8) NOT NULL DEFAULT '',
                phone VARCHAR(32) NOT NULL,
                phone_normalized VARCHAR(32) NOT NULL UNIQUE,
                email VARCHAR(180) NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                is_active SMALLINT NOT NULL DEFAULT 1,
                agreed_terms SMALLINT NOT NULL DEFAULT 0,
                auth_version INT NOT NULL DEFAULT 1,
                last_login TIMESTAMPTZ NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )");
        }
    } catch (Throwable $e) {
        error_log('Members schema ensure failed: ' . get_class($e));
    }
}

function jhd_countries(): array {
    return [
        'AF' => ['name' => 'افغانستان', 'dial' => '93'],
        'IR' => ['name' => 'ایران', 'dial' => '98'],
        'IQ' => ['name' => 'عراق', 'dial' => '964'],
        'PK' => ['name' => 'پاکستان', 'dial' => '92'],
        'TR' => ['name' => 'ترکیه', 'dial' => '90'],
        'SA' => ['name' => 'عربستان سعودی', 'dial' => '966'],
        'AE' => ['name' => 'امارات', 'dial' => '971'],
        'QA' => ['name' => 'قطر', 'dial' => '974'],
        'KW' => ['name' => 'کویت', 'dial' => '965'],
        'OM' => ['name' => 'عمان', 'dial' => '968'],
        'BH' => ['name' => 'بحرین', 'dial' => '973'],
        'LB' => ['name' => 'لبنان', 'dial' => '961'],
        'SY' => ['name' => 'سوریه', 'dial' => '963'],
        'JO' => ['name' => 'اردن', 'dial' => '962'],
        'YE' => ['name' => 'یمن', 'dial' => '967'],
        'EG' => ['name' => 'مصر', 'dial' => '20'],
        'IN' => ['name' => 'هند', 'dial' => '91'],
        'GB' => ['name' => 'بریتانیا', 'dial' => '44'],
        'DE' => ['name' => 'آلمان', 'dial' => '49'],
        'US' => ['name' => 'ایالات متحده', 'dial' => '1'],
        'CA' => ['name' => 'کانادا', 'dial' => '1'],
        'AU' => ['name' => 'استرالیا', 'dial' => '61'],
        'TJ' => ['name' => 'تاجیکستان', 'dial' => '992'],
        'UZ' => ['name' => 'ازبکستان', 'dial' => '998'],
        'OTHER' => ['name' => 'سایر کشورها', 'dial' => ''],
    ];
}

function normalizePhone(string $countryCode, string $phone): string {
    $dial = preg_replace('/\D+/', '', $countryCode) ?? '';
    $num = preg_replace('/\D+/', '', $phone) ?? '';
    $num = ltrim($num, '0');
    if ($dial !== '' && str_starts_with($num, $dial)) {
        $num = substr($num, strlen($dial));
        $num = ltrim($num, '0');
    }
    if ($num === '') return '';
    return $dial !== '' ? '+' . $dial . $num : '+' . $num;
}

function isMemberLoggedIn(): bool {
    startSecureSession();
    if (empty($_SESSION['member_id'])) return false;
    if (($_SESSION['last_member_activity'] ?? 0) < time() - SESSION_LIFETIME) {
        unset($_SESSION['member_id'], $_SESSION['member_name'], $_SESSION['member_auth_version'], $_SESSION['last_member_activity']);
        return false;
    }
    try {
        ensureMembersSchema();
        $stmt = getDB()->prepare('SELECT is_active, auth_version, full_name FROM members WHERE id=?');
        $stmt->execute([(int)$_SESSION['member_id']]);
        $row = $stmt->fetch();
    } catch (Throwable $e) {
        return false;
    }
    if (!$row || (int)$row['is_active'] !== 1 || (int)$row['auth_version'] !== (int)($_SESSION['member_auth_version'] ?? 0)) {
        unset($_SESSION['member_id'], $_SESSION['member_name'], $_SESSION['member_auth_version'], $_SESSION['last_member_activity']);
        return false;
    }
    $_SESSION['member_name'] = $row['full_name'];
    $_SESSION['last_member_activity'] = time();
    return true;
}

function requireMember(): void {
    if (!isMemberLoggedIn()) {
        header('Location: ' . loginUrl());
        exit;
    }
}

function currentMember(): array {
    startSecureSession();
    return [
        'id'   => (int)($_SESSION['member_id'] ?? 0),
        'name' => (string)($_SESSION['member_name'] ?? ''),
    ];
}

function loginMember(string $identifier, string $password): bool {
    if (strlen($identifier) > 180 || strlen($password) > 4096) return false;
    ensureMembersSchema();
    $db = getDB();
    $ipKey = hash('sha256', 'member-ip:' . clientIp());
    $idKey = hash('sha256', 'member:' . mb_strtolower(trim($identifier)));
    if (recordLoginAttempt($db, $ipKey) > 50) return false;
    if (recordLoginAttempt($db, $idKey) > 8) return false;

    $ident = trim($identifier);
    $member = null;
    if (str_contains($ident, '@')) {
        $stmt = $db->prepare('SELECT * FROM members WHERE email=? LIMIT 1');
        $stmt->execute([mb_strtolower($ident)]);
        $member = $stmt->fetch() ?: null;
    } else {
        $normalized = normalizePhone('', $ident);
        $stmt = $db->prepare('SELECT * FROM members WHERE phone_normalized=? OR phone=? LIMIT 1');
        $stmt->execute([$normalized !== '' ? $normalized : $ident, $ident]);
        $member = $stmt->fetch() ?: null;
        if (!$member) {
            $stmt = $db->prepare('SELECT * FROM members WHERE phone_normalized LIKE ? LIMIT 1');
            $tail = '%' . preg_replace('/\D+/', '', $ident);
            $stmt->execute([$tail]);
            $member = $stmt->fetch() ?: null;
        }
    }
    if (!$member) {
        password_verify($password, '$2y$10$usesomesillystringfore7wTCnyKPeogVA6awaz8iYupZHBMjqZ');
        return false;
    }
    if ((int)$member['is_active'] !== 1) return false;
    $stored = (string)($member['password'] ?? '');
    if (!jhd_password_is_hash($stored) || !password_verify($password, $stored)) return false;

    startSecureSession();
    $keepCsrf = $_SESSION[CSRF_TOKEN_NAME] ?? null;
    $keepAdmin = [
        'admin_id' => $_SESSION['admin_id'] ?? null,
        'admin_user' => $_SESSION['admin_user'] ?? null,
        'admin_name' => $_SESSION['admin_name'] ?? null,
        'admin_role' => $_SESSION['admin_role'] ?? null,
        'auth_version' => $_SESSION['auth_version'] ?? null,
        'last_activity' => $_SESSION['last_activity'] ?? null,
    ];
    session_regenerate_id(true);
    $_SESSION = [];
    if (is_string($keepCsrf) && $keepCsrf !== '') $_SESSION[CSRF_TOKEN_NAME] = $keepCsrf;
    foreach ($keepAdmin as $k => $v) {
        if ($v !== null) $_SESSION[$k] = $v;
    }
    $_SESSION['member_id'] = (int)$member['id'];
    $_SESSION['member_name'] = (string)$member['full_name'];
    $_SESSION['member_auth_version'] = (int)($member['auth_version'] ?? 1);
    $_SESSION['last_member_activity'] = time();
    $db->prepare('DELETE FROM login_limits WHERE limit_key=?')->execute([$idKey]);
    $nowSql = databaseDriver() === 'sqlite' ? "datetime('now')" : 'NOW()';
    $db->prepare("UPDATE members SET last_login = $nowSql WHERE id = ?")->execute([(int)$member['id']]);
    return true;
}

function registerMember(array $data): array {
    ensureMembersSchema();
    $name = trim((string)($data['full_name'] ?? ''));
    $country = (string)($data['country'] ?? '');
    $phone = trim((string)($data['phone'] ?? ''));
    $email = mb_strtolower(trim((string)($data['email'] ?? '')));
    $password = (string)($data['password'] ?? '');
    $confirm = (string)($data['password_confirm'] ?? '');
    $agreed = !empty($data['agreed_terms']);

    $countries = jhd_countries();
    if (!isset($countries[$country])) return ['ok' => false, 'error' => 'کشور انتخاب‌شده معتبر نیست.'];
    $dial = (string)$countries[$country]['dial'];
    $countryName = (string)$countries[$country]['name'];

    if (mb_strlen($name) < 2 || mb_strlen($name) > 120) return ['ok' => false, 'error' => 'نام را به‌درستی وارد کنید.'];
    if (!$agreed) return ['ok' => false, 'error' => 'برای ثبت‌نام باید با قوانین سایت موافق باشید.'];
    if (strlen($password) < 8 || strlen($password) > 4096) return ['ok' => false, 'error' => 'رمز عبور باید حداقل ۸ نویسه باشد.'];
    if (!hash_equals($password, $confirm)) return ['ok' => false, 'error' => 'تکرار رمز عبور مطابقت ندارد.'];
    if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) return ['ok' => false, 'error' => 'ایمیل واردشده معتبر نیست.'];

    $normalized = normalizePhone($dial, $phone);
    if ($normalized === '' || strlen($normalized) < 8) return ['ok' => false, 'error' => 'شماره تلفن معتبر نیست.'];

    $db = getDB();
    $ipKey = hash('sha256', 'member-reg:' . clientIp());
    if (recordLoginAttempt($db, $ipKey) > 20) return ['ok' => false, 'error' => 'تعداد تلاش‌ها بیش از حد است. بعداً دوباره تلاش کنید.'];

    $dup = $db->prepare('SELECT id FROM members WHERE phone_normalized=? LIMIT 1');
    $dup->execute([$normalized]);
    if ($dup->fetch()) return ['ok' => false, 'error' => 'امکان ایجاد حساب با این اطلاعات وجود ندارد.'];
    if ($email !== '') {
        $dupE = $db->prepare('SELECT id FROM members WHERE email=? LIMIT 1');
        $dupE->execute([$email]);
        if ($dupE->fetch()) return ['ok' => false, 'error' => 'امکان ایجاد حساب با این اطلاعات وجود ندارد.'];
    }

    $hash = password_hash($password, PASSWORD_DEFAULT);
    $sql = 'INSERT INTO members (full_name, country, country_code, phone, phone_normalized, email, password, is_active, agreed_terms, auth_version) VALUES (?,?,?,?,?,?,?,1,1,1)';
    if (databaseDriver() === 'pgsql') {
        $stmt = $db->prepare($sql . ' RETURNING id');
        $stmt->execute([$name, $countryName, $dial, $phone, $normalized, $email !== '' ? $email : null, $hash]);
        $id = (int)$stmt->fetchColumn();
    } else {
        $stmt = $db->prepare($sql);
        $stmt->execute([$name, $countryName, $dial, $phone, $normalized, $email !== '' ? $email : null, $hash]);
        $id = (int)$db->lastInsertId();
    }
    if ($id < 1) return ['ok' => false, 'error' => 'ثبت‌نام انجام نشد. دوباره تلاش کنید.'];

    startSecureSession();
    session_regenerate_id(true);
    $_SESSION['member_id'] = $id;
    $_SESSION['member_name'] = $name;
    $_SESSION['member_auth_version'] = 1;
    $_SESSION['last_member_activity'] = time();
    return ['ok' => true, 'id' => $id];
}

function changeMemberPassword(int $memberId, string $current, string $next): bool {
    if ($memberId < 1 || strlen($next) < 8 || strlen($next) > 4096) return false;
    ensureMembersSchema();
    $stmt = getDB()->prepare('SELECT password FROM members WHERE id=? AND is_active=1');
    $stmt->execute([$memberId]);
    $hash = (string)$stmt->fetchColumn();
    if (!jhd_password_is_hash($hash) || !password_verify($current, $hash)) return false;
    getDB()->prepare('UPDATE members SET password=?, auth_version = COALESCE(auth_version,1)+1 WHERE id=?')
        ->execute([password_hash($next, PASSWORD_DEFAULT), $memberId]);
    startSecureSession();
    $_SESSION['member_auth_version'] = (int)($_SESSION['member_auth_version'] ?? 1) + 1;
    return true;
}

function logoutMember(): void {
    startSecureSession();
    unset($_SESSION['member_id'], $_SESSION['member_name'], $_SESSION['member_auth_version'], $_SESSION['last_member_activity']);
    header('Location: ' . url());
    exit;
}
